# Generated by Django 5.2 on 2025-08-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('populacao', models.PositiveIntegerField(help_text='População total da cidade')),
                ('pib_per_capita', models.DecimalField(decimal_places=2, help_text='PIB per capita anual', max_digits=12)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.JSONField(help_text='Parâmetros usados na simulação')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to='simulacao.cidade')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.JSONField(help_text='Resultados agregados da simulação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('simulacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='simulacao.simulacao')),
            ],
        ),
    ]
