# Generated by Django 5.2.5 on 2025-10-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='pib_per_capita',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='populacao',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='resultado',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='parametros',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='ImpactoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_simulacao', models.CharField(blank=True, help_text='Dê um nome para sua simulação', max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('numero_turistas', models.PositiveIntegerField(help_text='Quantos turistas visitaram?')),
                ('gasto_medio', models.DecimalField(decimal_places=2, help_text='Quanto cada turista gasta por dia? (R$)', max_digits=10)),
                ('duracao_estadia', models.PositiveIntegerField(help_text='Quantos dias eles ficam?')),
                ('cidades_visitadas', models.PositiveIntegerField(default=1, help_text='Quantas cidades eles visitam?')),
                ('simulacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impacto', to='simulacao.simulacao')),
            ],
            options={
                'verbose_name': 'Cálculo de Impacto Econômico',
                'verbose_name_plural': 'Cálculos de Impacto Econômico',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
