# Generated by Django 5.2.5 on 2025-08-13 14:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AlterModelOptions(
            name='simulacao',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Simulação', 'verbose_name_plural': 'Simulações'},
        ),
        migrations.AddField(
            model_name='cidade',
            name='area_km2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='cobertura_vegetal_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de cobertura vegetal da cidade', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='emissao_co2_per_capita',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Emissão de CO2 per capita (toneladas/ano)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='energia_renovavel_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de energia renovável utilizada', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.CharField(default='PA', max_length=50),
        ),
        migrations.AddField(
            model_name='cidade',
            name='indice_sustentabilidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Índice de sustentabilidade da cidade (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cidade',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50),
        ),
        migrations.AddField(
            model_name='cidade',
            name='transporte_publico_sustentavel',
            field=models.BooleanField(default=False, help_text='Possui transporte público sustentável'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='alternativas_sustentaveis',
            field=models.TextField(blank=True, help_text='Sugestões de alternativas mais sustentáveis'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='economia_local_impacto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Impacto na economia local (R$)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='emissao_co2_hospedagem',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Emissão de CO2 da hospedagem (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='emissao_co2_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Emissão total de CO2 da viagem (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='emissao_co2_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Emissão de CO2 do transporte (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='impacto_ambiental',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='metas_cop30_alinhamento',
            field=models.TextField(blank=True, help_text='Como a viagem se alinha com as metas da COP 30'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='pontuacao_sustentabilidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pontuação de sustentabilidade (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='recomendacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='atividades_sustentaveis',
            field=models.BooleanField(default=True, help_text='Prioriza atividades sustentáveis'),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='compensacao_carbono',
            field=models.BooleanField(default=False, help_text='Deseja compensar emissões de carbono'),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='data_viagem',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='duracao_dias',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='meio_transporte_principal',
            field=models.CharField(blank=True, choices=[('aviao', 'Avião'), ('onibus', 'Ônibus'), ('carro', 'Carro'), ('trem', 'Trem'), ('barco', 'Barco')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='tipo_hospedagem',
            field=models.CharField(blank=True, choices=[('hotel_sustentavel', 'Hotel Sustentável'), ('hotel_convencional', 'Hotel Convencional'), ('pousada_local', 'Pousada Local'), ('hostel', 'Hostel'), ('casa_local', 'Casa de Família Local')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='pib_per_capita',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='populacao',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='resultado',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='parametros',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Turista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('interesse_sustentabilidade', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', help_text='Nível de interesse em turismo sustentável', max_length=20)),
                ('preferencia_transporte', models.CharField(choices=[('publico', 'Transporte Público'), ('bicicleta', 'Bicicleta'), ('caminhada', 'Caminhada'), ('carro_eletrico', 'Carro Elétrico'), ('carro_hibrido', 'Carro Híbrido'), ('carro_combustivel', 'Carro a Combustível')], default='publico', max_length=30)),
                ('participante_cop30', models.BooleanField(default=False, help_text='Está participando da COP 30')),
                ('cidade_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turistas_origem', to='simulacao.cidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='simulacao',
            name='turista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes', to='simulacao.turista'),
        ),
    ]
