# Generated by Django 5.0.1 on 2025-09-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='pib_per_capita',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='populacao',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='resultado',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='parametros',
            field=models.JSONField(),
        ),
    ]
