# Generated by Django 5.2.5 on 2025-08-20 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0002_alter_cidade_options_alter_relatorio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao',
            name='cenario',
            field=models.CharField(choices=[('conservador', 'Conservador'), ('realista', 'Realista'), ('otimista', 'Otimista')], default='realista', help_text='Cenário de simulação', max_length=20),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='cobertura_vegetal_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de cobertura vegetal da cidade', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='energia_renovavel_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de energia renovável utilizada', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='indice_sustentabilidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Índice de sustentabilidade da cidade (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='pontuacao_sustentabilidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pontuação de sustentabilidade (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=20),
        ),
    ]
