# Generated by Django 5.0.1 on 2025-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0002_alter_cidade_pib_per_capita_alter_cidade_populacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.CharField(default='Pará', help_text='Unidade federativa (default Pará)', max_length=50),
        ),
    ]
