# Generated by Django 5.2.5 on 2025-10-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0002_alter_cidade_pib_per_capita_alter_cidade_populacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactoeconomico',
            name='cidades_visitadas',
        ),
    ]
