# Generated by Django 5.0.1 on 2025-09-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0003_cidade_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='alternativas_sustentaveis',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='economia_local_impacto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='emissao_co2_hospedagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='emissao_co2_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='emissao_co2_transporte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='impacto_ambiental',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='metas_cop30_alinhamento',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='pontuacao_sustentabilidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='recomendacoes',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='atividades_sustentaveis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='cenario',
            field=models.CharField(default='realista', max_length=20),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='compensacao_carbono',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='data_viagem',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='duracao_estadia',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='gasto_medio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='meio_transporte_principal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='numero_turistas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='orcamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='status',
            field=models.CharField(default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='tipo_hospedagem',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='turista_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
