# Generated by Django 5.2.5 on 2025-08-20 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0003_simulacao_cenario_alter_cidade_cobertura_vegetal_pct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.CharField(default='PA', max_length=500000),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=500000, unique=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='pais',
            field=models.CharField(default='Brasil', max_length=500000),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='cenario',
            field=models.CharField(choices=[('conservador', 'Conservador'), ('realista', 'Realista'), ('otimista', 'Otimista')], default='realista', help_text='Cenário de simulação', max_length=500000),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='meio_transporte_principal',
            field=models.CharField(blank=True, choices=[('aviao', 'Avião'), ('onibus', 'Ônibus'), ('carro', 'Carro'), ('trem', 'Trem'), ('barco', 'Barco')], max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=500000),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='tipo_hospedagem',
            field=models.CharField(blank=True, choices=[('hotel_sustentavel', 'Hotel Sustentável'), ('hotel_convencional', 'Hotel Convencional'), ('pousada_local', 'Pousada Local'), ('hostel', 'Hostel'), ('casa_local', 'Casa de Família Local')], max_length=500000, null=True),
        ),
        migrations.AlterField(
            model_name='turista',
            name='email',
            field=models.EmailField(max_length=500000, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='turista',
            name='interesse_sustentabilidade',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', help_text='Nível de interesse em turismo sustentável', max_length=500000),
        ),
        migrations.AlterField(
            model_name='turista',
            name='nome',
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name='turista',
            name='preferencia_transporte',
            field=models.CharField(choices=[('publico', 'Transporte Público'), ('bicicleta', 'Bicicleta'), ('caminhada', 'Caminhada'), ('carro_eletrico', 'Carro Elétrico'), ('carro_hibrido', 'Carro Híbrido'), ('carro_combustivel', 'Carro a Combustível')], default='publico', max_length=500000),
        ),
        migrations.AlterField(
            model_name='turista',
            name='telefone',
            field=models.CharField(blank=True, max_length=500000),
        ),
    ]
