# Generated by GitHub Copilot on 2025-10-01

from django.db import migrations


def drop_unused_columns(apps, schema_editor):
    simulacao_model = apps.get_model("simulacao", "Simulacao")
    table_name = simulacao_model._meta.db_table

    extra_columns = {
        "atividades_sustentaveis",
        "cenario",
        "compensacao_carbono",
        "data_fim",
        "data_viagem",
        "duracao_estadia",
        "gasto_medio",
        "meio_transporte_principal",
        "numero_turistas",
        "orcamento",
        "status",
        "tipo_hospedagem",
        "turista_id",
    }

    connection = schema_editor.connection
    introspection = connection.introspection

    with connection.cursor() as cursor:
        existing_columns = {
            column.name for column in introspection.get_table_description(cursor, table_name)
        }

    columns_to_drop = existing_columns & extra_columns

    for column in columns_to_drop:
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table_name)} DROP COLUMN {schema_editor.quote_name(column)}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("simulacao", "0003_remove_impactoeconomico_cidades_visitadas"),
    ]

    operations = [
        migrations.RunPython(drop_unused_columns, migrations.RunPython.noop),
    ]
