# Generated by Django 5.2.5 on 2025-08-20 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0004_alter_cidade_estado_alter_cidade_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao',
            name='gasto_medio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gasto médio por turista por dia (R$)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='numero_turistas',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade de turistas no cenário'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.CharField(default='PA', max_length=50),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='cenario',
            field=models.CharField(choices=[('conservador', 'Conservador'), ('realista', 'Realista'), ('otimista', 'Otimista')], default='realista', help_text='Cenário de simulação', max_length=20),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='meio_transporte_principal',
            field=models.CharField(blank=True, choices=[('aviao', 'Avião'), ('onibus', 'Ônibus'), ('carro', 'Carro'), ('trem', 'Trem'), ('barco', 'Barco')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='tipo_hospedagem',
            field=models.CharField(blank=True, choices=[('hotel_sustentavel', 'Hotel Sustentável'), ('hotel_convencional', 'Hotel Convencional'), ('pousada_local', 'Pousada Local'), ('hostel', 'Hostel'), ('casa_local', 'Casa de Família Local')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='turista',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='turista',
            name='interesse_sustentabilidade',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', help_text='Nível de interesse em turismo sustentável', max_length=20),
        ),
        migrations.AlterField(
            model_name='turista',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='turista',
            name='preferencia_transporte',
            field=models.CharField(choices=[('publico', 'Transporte Público'), ('bicicleta', 'Bicicleta'), ('caminhada', 'Caminhada'), ('carro_eletrico', 'Carro Elétrico'), ('carro_hibrido', 'Carro Híbrido'), ('carro_combustivel', 'Carro a Combustível')], default='publico', max_length=30),
        ),
        migrations.AlterField(
            model_name='turista',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
