# Generated by GitHub Copilot on 2025-10-01

from django.db import migrations


def drop_table_columns(table_model, columns_to_remove, schema_editor):
    table_name = table_model._meta.db_table
    connection = schema_editor.connection
    introspection = connection.introspection

    with connection.cursor() as cursor:
        existing_columns = {
            column.name for column in introspection.get_table_description(cursor, table_name)
        }

    for column in existing_columns & columns_to_remove:
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table_name)} DROP COLUMN {schema_editor.quote_name(column)}"
        )


def drop_city_and_report_columns(apps, schema_editor):
    cidade_model = apps.get_model("simulacao", "Cidade")
    relatorio_model = apps.get_model("simulacao", "Relatorio")

    drop_table_columns(
        cidade_model,
        {"estado"},
        schema_editor,
    )

    drop_table_columns(
        relatorio_model,
        {
            "alternativas_sustentaveis",
            "atualizado_em",
            "economia_local_impacto",
            "emissao_co2_hospedagem",
            "emissao_co2_total",
            "emissao_co2_transporte",
            "impacto_ambiental",
            "metas_cop30_alinhamento",
            "pontuacao_sustentabilidade",
            "recomendacoes",
        },
        schema_editor,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("simulacao", "0004_cleanup_simulacao_table"),
    ]

    operations = [
        migrations.RunPython(drop_city_and_report_columns, migrations.RunPython.noop),
    ]
