# Generated by Django 5.2.5 on 2025-08-20 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0005_simulacao_gasto_medio_simulacao_numero_turistas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacao',
            name='duracao_dias',
        ),
        migrations.AddField(
            model_name='simulacao',
            name='data_fim',
            field=models.DateField(blank=True, help_text='Data final calculada', null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='duracao_estadia',
            field=models.PositiveIntegerField(default=1, help_text='Duração da estadia em dias'),
        ),
        migrations.AlterField(
            model_name='turista',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('dias', models.PositiveIntegerField(blank=True, help_text='Quantidade de dias nesta cidade', null=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='simulacao.cidade')),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerarios', to='simulacao.simulacao')),
            ],
            options={
                'ordering': ['simulacao', 'ordem'],
                'unique_together': {('simulacao', 'cidade', 'ordem')},
            },
        ),
    ]
